# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows:
1. The first a random number from 1 to 4
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [2]:
serie1 = pd.Series(np.random.randint(1, high=4, size=100))
serie2 = pd.Series(np.random.randint(1, high=3, size=100))
serie3 = pd.Series(np.random.randint(10000, high=30000, size=100))
serie3

0     23496
1     24103
2     18028
3     29803
4     17466
      ...
95    16611
96    13942
97    25623
98    19019
99    19031
Length: 100, dtype: int64

### Step 3. Let's create a DataFrame by joinning the Series by column

In [7]:
df = pd.DataFrame(pd.concat([serie1, serie2, serie3], axis=1))
df

    0  1      2
0   3  2  23496
1   3  2  24103
2   3  1  18028
3   2  2  29803
4   1  1  17466
.. .. ..    ...
95  2  1  16611
96  3  2  13942
97  1  2  25623
98  2  1  19019
99  1  2  19031

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [8]:
df.rename({0:'bedrs', 1 : 'bathrs', 2 : 'price_sqr_meter'},axis=1, inplace=True)
df

    bedrs  bathrs  price_sqr_meter
0       3       2            23496
1       3       2            24103
2       3       1            18028
3       2       2            29803
4       1       1            17466
..    ...     ...              ...
95      2       1            16611
96      3       2            13942
97      1       2            25623
98      2       1            19019
99      1       2            19031

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [17]:
bigcolumn = pd.concat([serie1, serie2, serie3]).to_frame()
bigcolumn

        0
0       3
1       3
2       3
3       2
4       1
..    ...
95  16611
96  13942
97  25623
98  19019
99  19031

[300 rows x 1 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [12]:
len(bigcolumn)

300

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [18]:
bigcolumn.reset_index(inplace=True,drop=True)

In [19]:
bigcolumn

         0
0        3
1        3
2        3
3        2
4        1
..     ...
295  16611
296  13942
297  25623
298  19019
299  19031

[300 rows x 1 columns]